In [6]:
import numpy as np
import sys
sys.path.append('../modules/') 
from vecnum import *

n = 3
s = 4

bit_array = number_to_bit_array(number=n,sites=s)
vector = bit_array_to_vector(bit_array)

print(n)
print(bit_array)
print(vector)

print(
    vector_to_bit_array(vector,sites=s)
)
print(
    bit_array_to_number(vector_to_bit_array(vector,sites=s))
)

3
[1 1 0 0]
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1 1 0 0]
3
