In [1]:
import numpy as np
import sys
sys.path.append('../../modules/') 
from config import hsd, num_threshold
from rule import rule_matrix
from tensor import *
from vecnum import *

In [5]:
order   = 1
rule    = 3
sites   = 4

operator    = rule_matrix(rule,order)
tensors     = operator_to_mpo(operator)
network     = create_network(tensors,sites)
matrix      = mpo_to_operator(network,round=True)
print(matrix,'\n')

for i in range(hsd**(sites)):
    state       = number_to_bit_array(i,sites)
    mps         = create_mps(state)
    vector      = bit_array_to_vector(state)
    vector2     = matrix@matrix@vector
    state_v     = vector_to_bit_array(vector2,sites)
    mps_2       = mpsoc(mps,network)
    mps_2       = optimize_mps(mps_2)
    mps_3       = mpsoc(mps_2,network)
    # for x in mps:
    #     print(x.shape)
    # for x in mps_2:
    #     print(x.shape)
    # for x in mps_3:
    #     print(x.shape) 
    state_2     = mps_to_array(mps_3)
    # print("1",state_v)
    # print("2",state_2)

    if not np.allclose(state_v,state_2):
        print(state)
        print("1",state_v)
        print("2",state_2)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]] 



In [2]:
state = [1,0,0,0,0,0]
mps = create_mps(state)
for tensor in mps:
    print(tensor.shape)


mps_2 = optimize_mps(mps)
for tensor in mps_2:
    print(tensor.shape)

print(mps_2)

(2, 1)
(2, 1, 1)
(2, 1, 1)
(2, 1, 1)
(2, 1, 1)
(2, 1)
(2, 1)
(2, 1, 1)
(2, 1, 1)
(2, 1, 1)
(2, 1, 1)
(2, 1)
[array([[-0.],
       [ 1.]]), array([[[1.]],

       [[0.]]]), array([[[1.]],

       [[0.]]]), array([[[1.]],

       [[0.]]]), array([[[1.]],

       [[0.]]]), array([[1.],
       [0.]])]


In [3]:
order   = 1
rule    = 6
sites   = 5

operator    = rule_matrix(rule,order)
tensors     = operator_to_mpo(operator)
network     = create_network(tensors,sites)
network     = product(network,network)

state = np.random.randint(0,hsd,sites)
mps         = create_mps(state)
for tensor in mps:
    print(tensor.shape)
print(mps_to_array(mps))

mps_2       = mpsoc(mps,network) 
mps_2       = mpsoc(mps_2,network) 
for tensor in mps_2:
    print(tensor.shape)
print(mps_to_array(mps_2))

mps_3       = optimize_mps(mps_2)
for tensor in mps_3:
    print(tensor.shape)
print(mps_to_array(mps_3))

(2, 1)
(2, 1, 1)
(2, 1, 1)
(2, 1, 1)
(2, 1)
[1 0 1 0 0]
(2, 16)
(2, 16, 16)
(2, 16, 16)
(2, 16, 16)
(2, 16)
[1 0 1 0 0]
(2, 2)
(2, 2, 1)
(2, 1, 1)
(2, 1, 1)
(2, 1)
[1 0 1 0 0]


In [35]:
order   = 1
rule    = 1
sites   = 2

operator    = rule_matrix(rule,order)
tensors     = operator_to_mpo(operator)
network     = create_network(tensors,sites)
matrix      = mpo_to_operator(network,round=True)
print(matrix,'\n')

for i in range(hsd**(sites)):
    state       = number_to_bit_array(i,sites)
    mps         = create_mps(state)
    vector      = bit_array_to_vector(state)
    vector2     = matrix@vector
    state_v     = vector_to_bit_array(vector2,sites)
    mps_2       = mpsoc(mps,network) 
    state_2     = mps_to_array(mps_2)
    if not np.allclose(state_v,state_2):
        print(state)


[[0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 1.]
 [0. 0. 0. 0.]] 



In [6]:
# order   = 1
# rule    = 15
# sites   = 3

# operator    = rule_matrix(rule,order)
# tensors     = operator_to_mpo(operator)
# network     = create_network(tensors,sites)
# network     = product(network,network)
# network     = product(network,network)

# for i in range(hsd**(sites)):
#     state       = number_to_bit_array(i,sites)
#     mps         = create_mps(state)


#     mps_2       = mpsoc(mps,network) 
#     for tensor in mps_2:
#         print(tensor.shape)
#     state_2     = mps_to_array(mps_2)
#     print(state_2)
