In [1]:
import numpy as np
import sys
sys.path.append('../../modules/') 
from config import hsd, num_threshold
from rule import rule_matrix
from tensor import *

d = 4
R = np.arange(1,d*d +1).reshape((d,d))

print(R)

tensors = operator_to_mpo(R)
# for tensor in tensors:
#     print(tensor.shape)
tensors = optimize_bonds(tensors)
# for tensor in tensors:
#     print(tensor.shape)
operator = mpo_to_operator(tensors)
print(operator)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]


In [3]:
d = 2**6
print(d)
R = np.arange(1,d*d +1).reshape((d,d))

print(R)

tensors = operator_to_mpo(R)
# for tensor in tensors:
#     print(tensor.shape)
tensors, e_e = optimize_bonds_middle(tensors)
# for tensor in tensors:
#     print(tensor.shape)
operator = mpo_to_operator(tensors,round=True)
print(operator)
print(e_e)

64
[[   1    2    3 ...   62   63   64]
 [  65   66   67 ...  126  127  128]
 [ 129  130  131 ...  190  191  192]
 ...
 [3905 3906 3907 ... 3966 3967 3968]
 [3969 3970 3971 ... 4030 4031 4032]
 [4033 4034 4035 ... 4094 4095 4096]]
[[1.000e+00 2.000e+00 3.000e+00 ... 6.200e+01 6.300e+01 6.400e+01]
 [6.500e+01 6.600e+01 6.700e+01 ... 1.260e+02 1.270e+02 1.280e+02]
 [1.290e+02 1.300e+02 1.310e+02 ... 1.900e+02 1.910e+02 1.920e+02]
 ...
 [3.905e+03 3.906e+03 3.907e+03 ... 3.966e+03 3.967e+03 3.968e+03]
 [3.969e+03 3.970e+03 3.971e+03 ... 4.030e+03 4.031e+03 4.032e+03]
 [4.033e+03 4.034e+03 4.035e+03 ... 4.094e+03 4.095e+03 4.096e+03]]
0.19372734885839496
