In [1]:
import numpy as np
import sys
sys.path.append('../../modules/') 
from config import hsd, order, num_threshold
from rule import rule_matrix
from tensor import *

# print(f'''CONFIG\nhsd:    {hsd}\norder:  {order}''')

d = 4
R = np.arange(1,d*d +1).reshape((d,d))

print(R)
print(R@R)

tensors = operator_to_mpo(R)
for tensor in tensors:
    print(tensor.shape)
tensors = product(tensors,tensors)
for tensor in tensors:
    print(tensor.shape)
operator = mpo_to_operator(tensors)
print(operator)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 90 100 110 120]
 [202 228 254 280]
 [314 356 398 440]
 [426 484 542 600]]
(2, 2, 2)
(2, 2, 2)
(2, 2, 4)
(2, 2, 4)
[[ 90. 100. 110. 120.]
 [202. 228. 254. 280.]
 [314. 356. 398. 440.]
 [426. 484. 542. 600.]]


In [2]:
d = 4
R = np.arange(1,d*d +1).reshape((d,d))

print(R)
# print(
#     np.kron(R,np.identity(hsd))
#     @\
#     np.kron(np.identity(hsd),R)
#     )
# print(
#     np.kron(R,np.identity(hsd*hsd))\
#     @\
#     np.kron(np.identity(hsd),np.kron(R,np.identity(hsd)))\
#     @\
#     np.kron(np.identity(hsd*hsd),R)
#     )
# print(
#     np.kron(R,np.identity(hsd**3))\
#     @\
#     np.kron(np.identity(hsd),np.kron(R,np.identity(hsd**2)))\
#     @\
#     np.kron(np.identity(hsd**2),np.kron(R,np.identity(hsd)))\
#     @\
#     np.kron(np.identity(hsd*hsd*hsd),R)
#     )

tensors = operator_to_mpo(R)
network = create_network(tensors,5)
print(mpo_to_operator(network))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[  2539.   3014.   3489. ...  10958.  12709.  14460.]
 [  4439.   4914.   5389. ...  17962.  19713.  21464.]
 [  4179.   4982.   5785. ...  16382.  19037.  21692.]
 ...
 [ 55607.  61554.  67501. ... 113514. 124577. 135640.]
 [ 52659.  62774.  72889. ... 103870. 120701. 137532.]
 [ 93119. 103234. 113349. ... 171194. 188025. 204856.]]


In [9]:
d = 8
R = np.arange(1,d*d +1).reshape((d,d))

# print(R)
# print(
#     np.kron(R,np.identity(hsd))
#     @\
#     np.kron(np.identity(hsd),R)
#     )
# print(
#     np.kron(R,np.identity(hsd*hsd))\
#     @\
#     np.kron(np.identity(hsd),np.kron(R,np.identity(hsd)))\
#     @\
#     np.kron(np.identity(hsd*hsd),R)
#     )
print(
    np.kron(R,np.identity(hsd**3))\
    @\
    np.kron(np.identity(hsd),np.kron(R,np.identity(hsd**2)))\
    @\
    np.kron(np.identity(hsd**2),np.kron(R,np.identity(hsd)))\
    @\
    np.kron(np.identity(hsd*hsd*hsd),R)
    )

tensors = operator_to_mpo(R)
for tensor in tensors:
    print(tensor.shape)
network = create_network(tensors,6)
for tensor in tensors:
    print(tensor.shape)
print(mpo_to_operator(network))

[[3.84740000e+06 3.99688000e+06 4.14636000e+06 ... 1.33096800e+07
  1.37440240e+07 1.41783680e+07]
 [5.04324000e+06 5.19272000e+06 5.34220000e+06 ... 1.67844320e+07
  1.72187760e+07 1.76531200e+07]
 [4.95140000e+06 5.14504000e+06 5.33868000e+06 ... 1.66620000e+07
  1.72080880e+07 1.77541760e+07]
 ...
 [1.19156776e+08 1.22688528e+08 1.26220280e+08 ... 1.86115120e+08
  1.90931160e+08 1.95747200e+08]
 [1.16992360e+08 1.21567696e+08 1.26143032e+08 ... 1.84854000e+08
  1.90912280e+08 1.96970560e+08]
 [1.53595048e+08 1.58170384e+08 1.62745720e+08 ... 2.33320240e+08
  2.39378520e+08 2.45436800e+08]]
(2, 2, 2)
(2, 2, 2, 2)
(2, 2, 2)
(2, 2, 2)
(2, 2, 2, 2)
(2, 2, 2)
[[3.84740000e+06 3.99688000e+06 4.14636000e+06 ... 1.33096800e+07
  1.37440240e+07 1.41783680e+07]
 [5.04324000e+06 5.19272000e+06 5.34220000e+06 ... 1.67844320e+07
  1.72187760e+07 1.76531200e+07]
 [4.95140000e+06 5.14504000e+06 5.33868000e+06 ... 1.66620000e+07
  1.72080880e+07 1.77541760e+07]
 ...
 [1.19156776e+08 1.22688528e+08 